---
- name: Install Apache
  yum:
    name: "httpd"
    state: "latest"

- name: Setting vagrant user in Apache
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    regexp: "^User apache"
    line: "User vagrant"
    state: "present"

- name: Setting vagrant group in Apache
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    regexp: "^Group apache"
    line: "Group vagrant"
    state: "present"

- name: Setting vhost Apache
  template:
    src: "vhost.tpl"
    dest: "/etc/httpd/conf.d/{{ item.server_name }}.conf"
  notify: restart httpd
  with_items: project_url

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "httpd"
    state: "started"
    enabled: "yes"
