---
- hosts: all
  sudo: true
  gather_facts: no

  vars_files:
    - /vars/vars.yml

  roles:
    - { role: initial, tags: ['initial'] }
    - { role: apache, tags: ['apache','setup'] }
    - { role: mysql, tags: ['mysql','setup'] }
    - { role: php, tags: ['php','setup','dev'] }
    - { role: symfony, tags: ['symfony','dev', 'project'] }
    - { role: hosts, tags: ['host','project','dev'] }
