---

- name: Verify if symfony is installed
  stat:
    path: "/usr/local/bin/symfony"
  register: symfony

- name: Install Symfony Installer
  shell: curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
  when: symfony.stat.exists == False

- name: Make Symfony Installer Executable
  shell: chmod a+x /usr/local/bin/symfony
  when: symfony.stat.exists == False

- name: Install Symfony Project
  shell: "cd {{ doc_root }} && /usr/local/bin/symfony new {{ item.doc_root }} {{ symfony_version }}"
  when: item.symfony_project
  with_items: project_url
  ignore_errors: yes
