---
- name: Install Mysql Packages
  yum:
    name: "{{ item }}"
    state: installed
    # enablerepo: {{ mysql_repo }}
  with_items: mysql_packages

- name: Ensure MySQL is started and enabled on boot.
  service: "name=mysqld state=started enabled=yes"
  notify: restart mysql

- name: Update MySQL root password for all root accounts.
  mysql_user:
    login_user: "root"
    login_password: ""
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
      - 127.0.0.1
      - ::1
      - localhost

- name: copy .my.cnf file with root password credentials
  template:
    src: ".my.cnf"
    dest: "/root/.my.cnf"
    owner: "root"
    mode: "0600"

- name: Remove anonymous MySQL user.
  mysql_user: "name='' state=absent"

- name: Remove MySQL test database.
  mysql_db: "name='test' state=absent"
